-- Seed file: optional demo data
-- Do not run in production. Use only for local development testing.
--
-- Preferred: run the Node seed script (200 demo coin requests)
--   npm run seed:demo -- --reset
--   npm run seed:demo -- --clear   (remove demo rows with request_id 1-200 only)
--
-- Optional env:
--   DEMO_USER_EMAIL=your@email.com
--
-- Super admin (full access to all users' data):
-- 1. Register via the app
-- 2. Run: npm run promote:super-admin -- your@email.com
--    Or set SUPER_ADMIN_EMAIL in .env.local and run: npm run promote:super-admin
-- 3. Or in Supabase SQL Editor:
--    UPDATE profiles SET role = 'admin' WHERE email = 'your@email.com';
