-- Seed file: optional demo data
-- Do not run in production. Use only for local development testing.
--
-- To create an admin user:
-- 1. Register via the app
-- 2. Run: UPDATE profiles SET role = 'admin' WHERE email = 'your@email.com';
